### ISSUE TITLE
AppLoading is deprecated

### ISSUE THREAD

**Issue by Liubsi** [Liubsi/nimloth-react-native#25]
Find something to replace it with.

**Comment by Marchwarden** [comment]
This was the message my terminal gave when loading the app on my phone.

expo-app-loading is deprecated in favor of expo-splash-screen: use SplashScreen.preventAutoHideAsync() and SplashScren.hideAsync() instead. https://docs.expo.dev/versions/latest/sdk/splash-screen/

**Comment by Liubsi** [comment]
Thats what we're trying to replace. The app runs fine, it's just a warning

**Comment by Marchwarden** [comment]
yeah, so should I replace app-loading with those two components, or would that not work.

**Comment by Liubsi** [comment]
No, replace it with null. We need to delay rendering because the font needs to load. Look at the Login page, we delay rendering there until the font has loaded.

**Comment by Marchwarden** [comment]
Okay

**Comment by Liubsi** [comment]
Fixed in alex/tentative-yarn-update
